version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          CC_TEST_REPORTER_ID: 6b03f339ba50b481cf2b653380f1ba8ccfdc0ab1e0a63aa835dae8d707a95490

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: npm test
      - run: ./cc-test-reporter after-build -t lcov --exit-code $?
