blank_issues_enabled: true
contact_links:
  - name: Need integrationhelp?
    url: mailto:support@readme.io?subject=I%20need%20help%20integrating%20a%20Metrics%20SDK!
    about: Email our support team!
