require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

# https://docs.rubocop.org/rubocop/cops_layout.html
Layout/LineLength:
  Max: 150

# https://docs.rubocop.org/rubocop/cops_metrics.html
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - spec/readme/*.rb
    - spec/readme/har/*.rb
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 20

# https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec
RSpec/AnyInstance:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Exclude:
    - spec/readme/*.rb
RSpec/MultipleExpectations:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html
Style/BlockDelimiters:
  Exclude:
    - spec/**/*
Style/ClassVars:
  Exclude:
    - 'lib/readme/metrics.rb'
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Exclude:
    - 'lib/readme/filter.rb'
    - 'lib/readme/metrics.rb'
Style/IfUnlessModifier:
  Exclude:
    - 'lib/readme/metrics.rb'
