readme:
  readmeApiKey: ${README_API_KEY}
  userdata:
    apiKey:
      source: header
      fieldName: X-User-Name
    email:
      source: header
      fieldName: X-User-Email
    label:
      source: header
      fieldName: X-User-Id

#readme:
#  readmeApiKey: ${README_API_KEY}
#  userdata:
#    apiKey:
#      source: jsonBody
#      fieldName: /owl-creator/name
#    email:
#      source: jsonBody
#      fieldName: /owl-creator/contacts/email
#    label:
#      source: jsonBody
#      fieldName: owl-creator/label

#readme:
#  readmeApiKey: ${README_API_KEY}
#  userdata:
#    apiKey:
#      source: jwt
#      fieldName: name
#    email:
#      source: jwt
#      fieldName: aud
#    label:
#      source: jwt
#      fieldName: user_id



