name: snippets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sdk-snippets

    strategy:
      fail-fast: false
      matrix:
        node-version:
          # see the following:
          # https://github.com/actions/setup-node?tab=readme-ov-file#supported-version-syntax
          # https://github.com/nvm-sh/nvm/issues/1998#issuecomment-594958684
          - lts/-1
          - lts/*
          - latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm test

  # This is being run separately since it's not playing nicely with Node 14.
  # Once we drop Node 14 support we can probably consolidate this again.
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sdk-snippets

    steps:
      - uses: actions/checkout@v4
      - run: npm ci --ignore-scripts
      - run: npm run lint
