name: snippets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sdk-snippets

    strategy:
      matrix:
        node-version:
          - 14
          - 16
          - 18

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Node 14 still ships with npm@6 so for compatibility reasons we're upping
      # this to match everything else.
      - name: Install npm@8
        if: matrix.node-version == '14'
        run: npm install -g npm@8

      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm test
